[package]
name = "blade_bar"
version = "0.1.0"
edition = "2024"

[dependencies]
gtk4 = "0.9.0"
gtk4-layer-shell = "0.5.0"
sysinfo = "0.30"
tokio = { version = "1.0", features = ["full"] }
glib = "0.18"
